version: '3.8'

services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports: 
      - 8080:90
    networks:
      - jointNet
      
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose: 
      - 8081:3000
    networks:
      - jointNet
    
  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  jointNet:
    driver: bridge