version: '3.8'

services:
  frontend:
    build:
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports: 
      - 8080:90
    networks:
      - jointNet
      
  backend: 
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    expose: 
      - 8081:3000
    networks:
      - jointNet

networks:
  jointNet:
    driver: bridge