apiVersion: v1
kind: Service
metadata:
  name: frontend-loadbalance-service
  namespace: k8s-training-frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
  - port: 90 # <-- This is the port ~exposed~ to the web
    targetPort: 90 # <-- this should refer to your spec.template.spec.containers.ports.containerPort
