apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: k8s-training-space
spec:
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app-container
        image: disgraceful/k8s-training:frontend-end-nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 90 # <-- this should be the port specified in your nginx conf file
